import { VerticalBox, Button } from "std-widgets.slint";
import { ContainerData, ContainerAction, ContainerStatus } from "./types.slint";

export component ContainerItem {
    in-out property <ContainerData> data;
    callback status_change(ContainerAction);
    if data.status == ContainerStatus.Running: Rectangle {
        border-radius: 5px;
        height: parent.height;
        background: #47c96e;
    }
    if data.status == ContainerStatus.Exited: Rectangle {
        border-radius: 5px;
        height: parent.height;
        background: #f8d5d5dd;
    }
    VerticalLayout {
        alignment: center;
        height: parent.height;
        padding-left: 10px;
        padding-right: 10px;
        HorizontalLayout {
            VerticalBox {
                alignment: center;
                Text {
                    font-weight: 700;
                    text: data.short-id;
                }
            }
            VerticalBox {
                alignment: center;
                Text {
                    font-weight: 700;
                    text: data.name;
                }
            }
            if data.status == ContainerStatus.Running: Button {
                width: 100px;
                text: "Stop";
                clicked => {
                    root.status_change(ContainerAction.Stop);
                }
            }
            if data.status == ContainerStatus.Exited: Button {
                width: 100px;
                text: "Start";
                clicked => {
                    root.status_change(ContainerAction.Start);
                }
            }
        }
    }
}